"""update metrics

Revision ID: 1ebe356c9902
Revises: 1c266e889de7
Create Date: 2024-10-23 22:36:20.681325

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ebe356c9902'
down_revision = '1c266e889de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('metric_type', sa.Enum('DAYS', 'APPLIES', name='subscriptionmetric'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'metric_type')
    # ### end Alembic commands ###
