"""fix user relations

Revision ID: 35b3a27887fa
Revises: 7686ac0cd3d5
Create Date: 2024-10-26 02:47:48.890414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35b3a27887fa'
down_revision = '7686ac0cd3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
