"""twoitial

Revision ID: 379c76245619
Revises: 7686ac0cd3d5
Create Date: 2025-02-03 03:45:09.170674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '379c76245619'
down_revision = '7686ac0cd3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_gateway', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('session_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subscription_plan_id', sa.Uuid(), nullable=False),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_session_session_id'), 'checkout_session', ['session_id'], unique=False)
    op.create_table('subscription_plan_benefit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_plan_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('payment', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('subscription_plan', sa.Column('is_best_choice', sa.Boolean(), nullable=False))
    op.add_column('subscription_plan', sa.Column('price_without_discount', sa.Float(), nullable=False))
    op.drop_column('subscription_plan', 'price_with_discount')
    op.drop_index('ix_user_stripe_customer_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_stripe_customer_id', 'user', ['stripe_customer_id'], unique=False)
    op.add_column('subscription_plan', sa.Column('price_with_discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('subscription_plan', 'price_without_discount')
    op.drop_column('subscription_plan', 'is_best_choice')
    op.alter_column('payment', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('subscription_plan_benefit')
    op.drop_index(op.f('ix_checkout_session_session_id'), table_name='checkout_session')
    op.drop_table('checkout_session')
    # ### end Alembic commands ###
