"""subs-plan feature

Revision ID: b378f8e269b7
Revises: 1ebe356c9902
Create Date: 2024-10-24 03:00:48.460011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b378f8e269b7'
down_revision = '1ebe356c9902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
