name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - staging
    env:
      ENVIRONMENT: staging
      DOMAIN: ${{ secrets.DOMAIN_STAGING }}
      FRONTEND_HOST: ${{ secrets.FRONTEND_HOST_STAGING }}
      STACK_NAME: ${{ secrets.STACK_NAME_STAGING }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER_STAGING }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_STAGING }}
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      MONGODB_PORT: ${{ secrets.MONGODB_PORT }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD_STAGING }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_STAGING }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET_STAGING }}
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL_STAGING }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID_STAGING }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY_STAGING }}
      S3_CONFIGS_BUCKET: ${{ secrets.S3_CONFIGS_BUCKET_STAGING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml build
      - run: docker compose -f docker-compose.yml up -d
