name: Deploy to Production

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ secrets.DOMAIN_PRODUCTION }}
      FRONTEND_HOST: ${{ secrets.FRONTEND_HOST_PRODUCTION }}
      BACKEND_HOST: ${{ secrets.BACKEND_HOST_PRODUCTION }}
      STACK_NAME: ${{ secrets.STACK_NAME_PRODUCTION }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER_PRODUCTION }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_PRODUCTION }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_PRODUCTION }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET_PRODUCTION }}
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL_PRODUCTION }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID_PRODUCTION }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY_PRODUCTION }}
      S3_CONFIGS_BUCKET: ${{ secrets.S3_CONFIGS_BUCKET_PRODUCTION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Decode KUBECONFIG
        run: |
          if [ -n "${{ secrets.KUBECONFIG }}" ]; then
            echo "${{ secrets.KUBECONFIG }}" | base64 -d > backend/kubeconfig.yaml
          fi
          
      - run: docker compose -f docker-compose.yml build
      - run: docker compose -f docker-compose.yml up -d
