name: Playwright Tests

on:
  push:
    branches:
    - main
    paths:
    - 'frontend/**'
    - 'backend/**'
  pull_request:
    types:
    - opened
    - synchronize
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'false'

jobs:

  test:
    env:
      DOMAIN: localhost
      FRONTEND_HOST: http://localhost:5173
      ENVIRONMENT: local
      PROJECT_NAME: "test"
      STACK_NAME: project
      BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173"
      SECRET_KEY: changethis
      FIRST_SUPERUSER: admin@example.com
      FIRST_SUPERUSER_PASSWORD: changethis
      SMTP_TLS: True
      SMTP_SSL: False
      SMTP_PORT: 587
      POSTGRES_SERVER: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changethis
      MONGODB_SERVER: localhost
      MONGODB_PORT: 27017
      MONGODB_DB: app
      MONGODB_USER: mongo
      MONGODB_PASSWORD: changethis
      S3_ENDPOINT_URL: http://localhost:9000
      S3_ACCESS_KEY_ID: changethis
      S3_SECRET_ACCESS_KEY: changethis
      S3_CONFIGS_BUCKET: configs
      DOCKER_IMAGE_BACKEND: backend
      DOCKER_IMAGE_FRONTEND: frontend
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
      with:
        limit-access-to-actor: true
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: frontend
    - run: docker compose build
    - run: docker compose down -v --remove-orphans
    - run: docker compose up -d --wait backend mailcatcher
    - name: Run Playwright tests
      run: npx playwright test --fail-on-flaky-tests --trace=retain-on-failure
      working-directory: frontend
    - run: docker compose down -v --remove-orphans
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
        include-hidden-files: true

  # https://github.com/marketplace/actions/alls-green#why
  e2e-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
